eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

microservices:
  payment:
    endpoint:
      uri: http://PAYMENT-SERVICE/payment/doPayment