spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Sandeep#123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

payment:
  endpoint: http://PAYMENT-SERVICE/payment/doPayment
